name: SPADES-Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{github.ref}}-${{github.head_ref}}-docs
  cancel-in-progress: true

jobs:
  Docs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install sphinx sphinx_rtd_theme
      - name: Configure
        run: cmake -B${{runner.workspace}}/build-docs ${{github.workspace}}/Docs
      - name: Build
        working-directory: ${{runner.workspace}}/build-docs
        run:  |
           echo "::add-matcher::.github/problem-matchers/sphinx.json"
           cmake --build ${{runner.workspace}}/build-docs
           touch ${{runner.workspace}}/build-docs/sphinx/html/.nojekyll
      # - name: Deploy
      #   if: github.event_name == 'push'
      #   uses: JamesIves/github-pages-deploy-action@releases/v3
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     BRANCH: gh-pages
      #     FOLDER: ${{runner.workspace}}/build-docs/sphinx/html
      #     SINGLE_COMMIT: true
