name: SPADES-Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{github.ref}}-${{github.head_ref}}-docs
  cancel-in-progress: true

jobs:
  Docs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends graphviz libenchant-2-dev
          python3 -m pip install --upgrade pip
          pip3 install sphinx sphinx_rtd_theme doxysphinx pyenchant sphinxcontrib-spelling
      - name: Doxygen install
        uses: ssciwr/doxygen-install@v1.6.0
        with:
          version: "1.12.0"
      - name: Configure
        run: |
          cmake -B ${{runner.workspace}}/build-docs \
            -DSPADES_ENABLE_DOCUMENTATION:BOOL=ON \
            ${{github.workspace}}
      - name: Build
        working-directory: ${{runner.workspace}}/build-docs
        run:  |
           echo "::add-matcher::.github/problem-matchers/sphinx.json"
           cmake --build ${{runner.workspace}}/build-docs -t docs 2>&1 | tee -a build-output.txt
           touch ${{runner.workspace}}/build-docs/Docs/sphinx/html/.nojekyll
      - name: Report
        working-directory: ${{runner.workspace}}/build-docs
        run: |
          echo "::add-matcher::.github/problem-matchers/sphinx.json"
          # Doxygen on ubuntu-latest is old and complains of unsupported tag
          grep -E "WARNING:|Warning:|warning:|ERROR:|Error:|error:" build-output.txt | sort | uniq | \
            awk 'BEGIN{i=0}{print $0}{i++}END{print "Warnings: "i}' > build-output-warnings.txt
          cat build-output-warnings.txt
          exit $(tail -n 1 build-output-warnings.txt | awk '{print $2}')
      # - name: Deploy
      #   if: github.event_name == 'push'
      #   uses: JamesIves/github-pages-deploy-action@releases/v3
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     BRANCH: gh-pages
      #     FOLDER: ${{runner.workspace}}/build-docs/Docs/sphinx/html
      #     SINGLE_COMMIT: true
